services:
  gemini-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gemini-api
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # depends_on:
    #   - gemini-db
    networks:
      - gemini-network
networks:
  gemini-network: