services:
  gemini-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gemini-api
    env_file:
      - .env
    ports:
      - 80:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # depends_on:
    #   - gemini-db
    networks:
      - gemini-network
  gemini-db:
    image: postgres:16-alpine
    container_name: gemini-db
    ports:
      - 5432:5432
    volumes:
      - .:/gemini-db/postgresql/data
    environment:
      - POSTGRES_PASSWORD=gemini
      - POSTGRES_USER=gemini
      - POSTGRES_DB=profile_svc_db
    networks:
      - gemini-network
networks:
  gemini-network: